apiVersion: v1
kind: Namespace
metadata:
  name: BRANCHNAME

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: birdnoise-BRANCHNAME
  namespace: BRANCHNAME
spec:
  rules:
    - host: BRANCHNAME.klucsik.duckdns.org
      http:
        paths:
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: birdnoise-svc-be
                port:
                  number: 80
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: birdnoise-svc-fe
                port:
                  number: 80

---
#be
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdnoise-be
  namespace: BRANCHNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: birdnoise
  template:
    metadata:
      labels:
        type: backend
        service: birdnoise
    spec:
      containers:
        - name: backend
          image: BE_IMAGETAG
          imagePullPolicy: Always
          env:
            - name: REDEPLOY_FLAG
              value: "BE_JENKINS_WILL_CHANGE_THIS_WHEN_REDEPLOY_NEEDED_BASED_ON_CHANGE"
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
---

apiVersion: v1
kind: Service
metadata:
  name: birdnoise-svc-be
  namespace: BRANCHNAME
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    type: backend
    service: birdnoise

---
#fe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdnoise-fe
  namespace: BRANCHNAME
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
      service: birdnoise
  template:
    metadata:
      labels:
        type: frontend
        service: birdnoise
    spec:
      containers:
        - name: frontend
          image: FE_IMAGETAG
          imagePullPolicy: Always
          env:
            - name: REDEPLOY_FLAG
              value: "FE_JENKINS_WILL_CHANGE_THIS_WHEN_REDEPLOY_NEEDED_BASED_ON_CHANGE"

---

apiVersion: v1
kind: Service
metadata:
  name: birdnoise-svc-fe
  namespace: BRANCHNAME
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: frontend
    service: birdnoise
