apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-ddns
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - echo url="https://www.duckdns.org/update?domains=klucsik&token=db7cb8ef-b5a6-475e-adf3-dfe7c2e534ef&ip=" | curl -k -K -
          restartPolicy: OnFailure