kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-repository
  namespace: jenkins #this should be the same as in jenkins settings
spec:
  storageClassName: longhorn-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G