kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-repository
  namespace: jenkins #this should be the same as in jenkins settings
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G