apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: maven:3.8.2-jdk-11-slim
      command: ["sleep", "1d"]  # this or any command that is basically a noop is required, so the containers will not exit prematurely
      resources:  # limits the resources your build container
        requests:
          memory: "200Mi"
          cpu: "300m"
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: maven-repository
          mountPath: /root/.m2

    - name: docker
      image: docker:20.10.8
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine

    - name: kubectl
      image: registry.klucsik.fun/kubectl #TODO change this dynamically
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"

    - name: newman
      image: postman/newman
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "300Mi"
          cpu: "300m"
        limits:
          memory: "2Gi"
      nodeSelector:
        kubernetes.io/arch: "amd64"

  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repository
      persistentVolumeClaim:
        claimName: maven-repository
