apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    function: "builder"
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: maven:3.8.2-jdk-11-slim
      imagePullPolicy:  IfNotPresent
      command: ["sleep", "1d"]  # this or any command that is basically a noop is required, so the containers will not exit prematurely
      resources:
        requests:
          memory: "50Mi"
          cpu: "30m"
      env:
        - name: TZ
          value: "Europe/Budapest"
      volumeMounts:
        - name: maven-repository
          mountPath: /root/.m2

    - name: docker
      image: registry.klucsik.fun/buildx
      imagePullPolicy:  IfNotPresent
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "50Mi"
          cpu: "30m"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine

    - name: kubectl
      image: registry.klucsik.fun/kubectl #TODO change this dynamically
      imagePullPolicy:  IfNotPresent
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "50Mi"
          cpu: "30m"

    - name: newman
      image: postman/newman
      imagePullPolicy:  IfNotPresent
      command: ["sleep", "1d"]
      nodeSelector:
        kubernetes.io/arch: "amd64"
      resources:
        requests:
          memory: "50Mi"
          cpu: "30m"

  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repository
      persistentVolumeClaim:
        claimName: maven-repository
