apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: maven
      image: maven:3.8.2-jdk-11-slim
      command: ["tail", "-f", "/dev/null"]  # this or any command that is bascially a noop is required, this is so that you don't overwrite the entrypoint of the base container
      resources:  # limits the resources your build contaienr
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
      volumeMounts:
        - name: maven-repository
          mountPath: /root/.m2

    - name: docker
      image: docker:20.10.8
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: maven-repository
      persistentVolumeClaim:
        claimName: maven-repository
